# Server
server.port=3000

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=ret0001

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=letmedinerestaurant@gmail.com
spring.mail.password=dbiuqlrvglvfjrse

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.recaptcha.secret=6LdrH-wsAAAAABX-D0Aur_pbZmlRP08MMtDhk5XQ

razorpay.key.id = rzp_test_Sr3Wysqx5rbOFB
razorpay.key.secret=tEqu7tM4umL62W42M2NFbjU7

#frontendUrl
# frontend.url = https://orchardsolvemb64.lntedutech.com/project/9542